name: build

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch: {}

jobs:
  data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Show ref
        run: |
          echo "$GITHUB_REF"
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: Remove software from the runner image
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get install -y -qq libicu-dev wget
          pip install pyicu awscli
          pip install -r requirements.txt
      - name: Parse the companies house data
        run: |
          python parse.py
      - name: Aggregate fragmented entities
        run: |
          sort -o data/combined.json data/psc_data.json data/base_data.json
          rm data/psc_data.json data/base_data.json
          mkdir -p data/export
	        zavod sorted-merge -o data/export/psc.json data/combined.json
      - name: Publish data to data.opensanctions.org
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync --no-progress --cache-control "public, max-age=64600" --metadata-directive REPLACE --acl public-read data/export s3://data.opensanctions.org/contrib/gb_coh_psc
